#-------------------------------------------------------------------
# EdxBuilder Strings
#-------------------------------------------------------------------
#
#
#   Author : Guillaume Plique
#   Organization : Sciences-Po Medialab
#   Version : 0.1.0
#   Language : English

# Main Strings
main:
    title: 'EdxBuilder'
    retrieving: 'Retrieving course info in : {{path}}//INFO'
    test: 'Testing...//INFO'
    course_name: 'Treating course: "{{course_name}}"//INFO'
    compiling: 'Compiling course to {{path}}//INFO'
    done: 'Done!//INFO'
errors:
    aborting: 'Aborting...//WARNING'
    course_not_found: 'Course layout not found.//ERROR'
    file_not_found: 'Subsequence file not found: {{path}}//ERROR'
