#-------------------------------------------------------------------
# EdxBuilder Strings
#-------------------------------------------------------------------
#
#
#   Author : Guillaume Plique
#   Organization : Sciences-Po Medialab
#   Version : 0.1.0
#   Language : English

# Main Strings
main:
    title: 'EdxBuilder'
    retrieving_layout: 'Retrieving course layout//VERBOSE'
    test: 'Testing...//INFO'